# Site settings
author: Karen Ercoli
title: ER Script
header-img: img/home-bg.png
email: karenercoli@gmail.com
copyright_name: Karen Ercoli
description: > # this means to ignore newlines until "baseurl:"
  from zero to hero? we'll soon find out
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kodekaren

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
